# La bibliothèque Numpy

In [1]:
import numpy as np

In [4]:
#on crée des arrays
arr1=np.array([1,3,6])
arr1
arr2= np.arange(3)
arr1+arr2

array([1, 4, 8])

In [15]:
#Créez un array bidimensionnel avec des valeurs quelconques, calculer le cube de cet array
arr3=np.array([[1,4,7],[3,5,8]])
arr3
type(arr3)

numpy.ndarray

In [21]:
arr4=np.array([1,4,7,3,5,8],dtype=float).reshape(2,3)
(arr4**3).shape

(2, 3)

In [25]:
#Construire une matrice rectangulaire de taille 3 x 2 avec une suite de nombres commençant à 5, 
#calculer le produit de la transposée par la matrice.

arr5=np.arange(5,11).reshape(3,2)
np.dot(arr5.T,arr5)

array([[155, 176],
       [176, 200]])

In [27]:
np.linalg.inv(np.dot(arr5.T,arr5))

array([[ 8.33333333, -7.33333333],
       [-7.33333333,  6.45833333]])

In [36]:
#Générer un array de nombres aléatoires puis remplacer les valeurs plus petites que 0 par 0. np.where()
arr6=np.random.randn(1000000)
arr6.shape
arr7=np.where(arr6<0,0,arr6)
np.min(arr7)
#Trier l’array obtenu np.sort
np.sort(arr7)

array([ 0.        ,  0.        ,  0.        , ...,  4.53503632,
        4.62140462,  4.71955622])

In [38]:
arr8=np.random.randn(1000000).reshape(10000,100)

In [45]:
#tri par colonne et recherche du max par colonne
np.var(np.sort(arr8,axis=0),axis=0)

array([ 1.01041204,  1.01094138,  1.00137112,  0.99560444,  0.99115526,
        0.98688413,  1.01347381,  1.00065853,  0.98719429,  0.986927  ,
        0.97569614,  0.9891849 ,  0.99446998,  1.01494226,  1.00428065,
        0.99320422,  0.98956797,  1.01122188,  0.99604708,  1.02633669,
        0.99979683,  0.9890084 ,  0.99265113,  1.02753269,  1.00230172,
        0.98455968,  1.00085162,  0.98825404,  1.01972779,  0.99450916,
        0.9848304 ,  1.01022825,  0.96274052,  0.99401097,  0.99824128,
        1.01027631,  0.98926931,  1.01116661,  0.99963052,  1.01402915,
        1.01288647,  0.99469587,  0.9925265 ,  1.04069237,  0.98325401,
        0.98809438,  0.99045174,  0.98845604,  0.98462625,  1.00570827,
        0.99322286,  0.99039459,  0.9962593 ,  0.99787602,  0.98233646,
        0.99853226,  0.99445129,  1.00849554,  0.98051947,  0.99237013,
        0.99207631,  0.98859653,  0.98508026,  0.99979598,  1.0189575 ,
        1.0060112 ,  1.00538162,  0.96292428,  0.99540254,  0.99

In [47]:
#sauvegarder cette matrice dans array.npy puis dans array.txt
np.save("array.npy",arr8)
np.savetxt("aaray.txt",arr8)

In [49]:
arr9=np.load("array.npy")

In [55]:
%pwd

'C:\\Users\\Emmanuel\\Desktop\\formation python'

In [56]:
arr9.shape

(10000, 100)